parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true

extends:
- fbjs
- plugin:import/errors
- plugin:import/warnings
- prettier
- prettier/flowtype
- prettier/react

plugins:
- flowtype
- react
- prettier

env:
  browser: true
  node: true

rules:
  strict: off
  prettier/prettier:
  - error
  - singleQuote: true
    trailingComma: all
    bracketSpacing: false
    jsxBracketSameLine: false
    parser: flow
  max-len:
  - error
  - code: 120
    ignoreUrls: true
  no-confusing-arrow: error
  no-mixed-operators: error
  no-unexpected-multiline: error
  import/no-unresolved:
  - off
  - commonjs: false
    amd: false

  overrides:
    - files: 'webpack/**/*.js'
      options:
        prettier/prettier:
          - error
          - singleQuote: true
            trailingComma: es5
            bracketSpacing: false
            jsxBracketSameLine: false
            parser: babylon
